In [2]:
import pandas as pd

In [3]:
import pandas as pd
import sqlite3
import json

In [4]:
orders = pd.read_csv("orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [5]:
with open("users.json", "r") as f:
    users = pd.DataFrame(json.load(f))

users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [6]:
conn = sqlite3.connect(":memory:")

with open("restaurants.sql", "r") as f:
    conn.executescript(f.read())

restaurants = pd.read_sql_query("SELECT * FROM restaurants", conn)
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [7]:
final_df = orders.merge(users, on="user_id", how="left") \
                 .merge(restaurants, on="restaurant_id", how="left")

final_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [8]:
final_df.to_csv("final_food_delivery_dataset.csv", index=False)
print("Final dataset saved successfully!")

Final dataset saved successfully!

In [9]:
gold_orders = final_df[final_df["membership"] == "Gold"].shape[0]
gold_orders

4987

In [10]:
hyderabad_revenue = round(final_df[final_df["city"] == "Hyderabad"]["total_amount"].sum())
hyderabad_revenue

1889367

In [11]:
final_df["user_id"].nunique()

2883

In [12]:
round(final_df[final_df["membership"] == "Gold"]["total_amount"].mean(), 2)

np.float64(797.15)

In [13]:
final_df[final_df["rating"] >= 4.5].shape[0]

3374